const images = {
  SignUp:{
    logo:require('../assets/logo.png'),
    user:require('../assets/SignUp/user.png'),
    eye:require('../assets/SignUp/eye.png'),
    lock:require('../assets/SignUp/lock.png'),
    email:require('../assets/SignUp/email.png'),
    phone:require('../assets/SignUp/phone.png'),
    eyeCrossed:require('../assets/SignUp/eye-crossed.png'),
  },
  Onboard:{
    page1:require("../assets/Onboard/page1.png"),
    page2:require("../assets/Onboard/page2.png"),
    page3:require("../assets/Onboard/page3.png"),
    
  },
  ForgotPassword:{
    sittingPerson:require("../assets/ForgotPassword/sittingPerson.png"),
    newPassword:require("../assets/ForgotPassword/newPassword.png"),
    success:require("../assets/ForgotPassword/success.png"),
    loader:require("../assets/ForgotPassword/loader.png"),
    backButton:require("../assets/ForgotPassword/back.png"),
  },
  BottomBar:{
    unfocusedHome:require("../assets/BottomBar/unfocusedHome.png"),
    focusedHome:require("../assets/BottomBar/focusedHome.png"),
    unfocusedOrders:require("../assets/BottomBar/unfocusedOrders.png"),
    focusedOrders:require("../assets/BottomBar/focusedOrders.png"),
    unfocusedProfile:require("../assets/BottomBar/unfocusedProfile.png"),
    focusedProfile:require("../assets/BottomBar/focusedProfile.png"),
  },
  Home:{
    heart:require("../assets/Home/Heart.png"),
    notification:require("../assets/Home/Notification.png"),
    zaid:require("../assets/Home/Zaid.jpg"),
    search:require("../assets/Home/search.png"),
    filter:require("../assets/Home/Filter.png"),
    star:require("../assets/Home/Star.png"),
    crop:require("../assets/Home/Image.png"),
    separator:require("../assets/Home/separator.png"),
  },
  SeeAll:{
    search:require("../assets/SeeAll/Search.png"),
  },
  Crop:{
    heart:require("../assets/Crop/Heart.png"),
  },
  Review:{
    whiteStar:require("../assets/Review/whiteStar.png"),
    greenStar:require("../assets/Review/greenStar.png"),
    whiteHeart:require("../assets/Review/whiteHeart.png"),
    greenHeart:require("../assets/Review/greenHeart.png"),
  },
  Search:{
    filter:require("../assets/Search/Filter.png"),
    notFound:require("../assets/Search/notFound.png"),
    cursor:require("../assets/Search/cursor.png"),
    remove:require("../assets/Search/remove.png"),
  },
  Order:{
    leave:require("../assets/Order/leave.png"),
  }
};

export default images;
